#ifndef PINOUT_H
#define PINOUT_H

#define AZIMUTH_FORWARD_PIN A2
#define AZIMUTH_BACKWARD_PIN A3
#define ELEVATION_FORWARD_PIN A4
#define ELEVATION_BACKWARD_PIN A5
#define RF_POWER_PIN A1
#define HOMMING_SWITCH_PIN A0

#define RED_LED_PIN 28
#define ACTIVITY_BUZZER_PIN 29

#define RF_BAND_0 2
#define RF_BAND_1 4
#define RF_BAND_2 5
#define RF_BAND_3 8
#define RF_BAND_4 3
#define RF_BAND_5 6
#define RF_BAND_6 7

#endif
